dungeons: true
textUri: not configured
dbName: not configured
collectionName: not configured
parameters:
    canPickupItem:
        default: false
    canManipulateArmorStand:
        default: false
    canEnterBed:
        default: false
    canUseBucket:
        default: false
    canDropItem:
        default: false
    canChangeExperience:
        default: false
    canFly:
        default: false
    canSneak: 
        default: true
    canSprint:
        default: true