main: yourselvs.dungeons.Dungeons
name: Dungeons
version: 2.0
author: yourselvs
description: A dungeon manager to allow servers to have timed dungeon courses.
commands:
    dungeon:
        description: Access to Dungeons commands.
        usage: /<command>
permissions:
    dungeon:
        default: true
    dungeon.info:
        default: op
    dungeon.join:
        default: op
    dungeon.forcejoin:
        default: op
    dungeon.forceleave:
        default: op
    dungeon.top:
        default: op
    dungeon.history:
        default: op
    dungeon.record:
        default: op
    dungeon.rank:
        default: op
    dungeon.create:
        default: op
    dungeon.command:
        default: op
    dungeon.checkpoint:
        default: op